# Generated by Django 5.2 on 2025-05-19 20:52

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'alergeno',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mesa',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nivel_picante', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('zona_preparacion', models.CharField(choices=[('COCINA', 'Cocina'), ('BARRA', 'Barra')], default='COCINA', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('PRINCIPAL', 'Principal'), ('BEBIDA', 'Bebida'), ('POSTRE', 'Postre')], default='PRINCIPAL', max_length=10)),
                ('aparece_en_carta', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('encargado', 'Encargado'), ('camarero', 'Camarero'), ('cocinero', 'Cocinero'), ('bartender', 'Bartender'), ('cliente', 'Cliente')], default='cliente', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PedidoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En Preparación'), ('SERVIDO', 'Servido'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('num_comensales', models.PositiveIntegerField(default=1)),
                ('notas', models.TextField(blank=True, null=True)),
                ('camarero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_mesa', to='titoPicantitoRestaurant.mesa')),
            ],
            options={
                'db_table': 'pedido_mesa',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En Preparación'), ('LISTO', 'Listo para Recoger'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_online', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido_online',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAlergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titoPicantitoRestaurant.alergeno')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titoPicantitoRestaurant.producto')),
            ],
            options={
                'db_table': 'producto_alergeno',
                'unique_together': {('producto', 'alergeno')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='alergenos',
            field=models.ManyToManyField(blank=True, through='titoPicantitoRestaurant.ProductoAlergeno', to='titoPicantitoRestaurant.alergeno'),
        ),
        migrations.CreateModel(
            name='LineaPedidoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preparado', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='titoPicantitoRestaurant.pedidoonline')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titoPicantitoRestaurant.producto')),
            ],
            options={
                'db_table': 'linea_pedido_online',
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='LineaPedidoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preparado', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='titoPicantitoRestaurant.pedidomesa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titoPicantitoRestaurant.producto')),
            ],
            options={
                'db_table': 'linea_pedido_mesa',
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
