# Generated by Django 5.2 on 2025-05-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomesa',
            name='tiene_nuevos_productos',
            field=models.BooleanField(default=False),
        ),
    ]
