# Generated by Django 5.2 on 2025-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0002_pedidomesa_tiene_nuevos_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomesa',
            name='notas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
