# Generated by Django 5.2 on 2025-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0003_alter_pedidomesa_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedidomesa',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineapedidomesa',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineapedidoonline',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineapedidoonline',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidomesa',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidomesa',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoalergeno',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoalergeno',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
