# Generated by Django 5.2 on 2025-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0004_lineapedidomesa_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergeno',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alergeno',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
