# Generated by Django 5.2 on 2025-05-23 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0005_alergeno_fecha_alta_alergeno_fecha_modificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_login', models.DateTimeField(auto_now_add=True)),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Login',
                'verbose_name_plural': 'Historial de Logins',
                'db_table': 'historial_login',
                'ordering': ['-fecha_login'],
            },
        ),
    ]
