# Generated by Django 5.2 on 2025-05-25 17:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0006_historiallogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
