# Generated by Django 5.2 on 2025-05-26 14:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0007_usuario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resena',
            },
        ),
        migrations.CreateModel(
            name='ResenaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titoPicantitoRestaurant.resena')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resena_usuario',
                'unique_together': {('resena', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='resenas',
            field=models.ManyToManyField(blank=True, through='titoPicantitoRestaurant.ResenaUsuario', to='titoPicantitoRestaurant.resena'),
        ),
    ]
