# Generated by Django 5.2 on 2025-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0008_resena_resenausuario_usuario_resenas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
