# Generated by Django 5.2 on 2025-06-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0010_reservamesa_reservausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamesa',
            name='fecha_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
