# Generated by Django 5.2 on 2025-06-10 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0011_reservamesa_fecha_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo_sugerencia', models.CharField(choices=[('PLATOS', 'Platos'), ('LOCAL', 'Local'), ('PEDIDOS', 'Pedidos')], default='LOCAL', max_length=10)),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sugerencia',
            },
        ),
        migrations.CreateModel(
            name='SugerenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titoPicantitoRestaurant.sugerencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sugerencia_usuario',
                'unique_together': {('sugerencia', 'usuario')},
            },
        ),
    ]
