# Generated by Django 5.2 on 2025-06-10 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titoPicantitoRestaurant', '0012_sugerencia_sugerenciausuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(choices=[('CAMARERO', 'Camarero'), ('COCINERO', 'Cocinero'), ('GESTOR', 'Gestor')], default='CAMARERO', max_length=10)),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='SolicitudUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titoPicantitoRestaurant.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitud_usuario',
                'unique_together': {('solicitud', 'usuario')},
            },
        ),
    ]
